version: "3.8"
services:
  catalog:
    build: ./catalog-service
    ports:
      - "3000:3000"

  order:
    build: ./order-service
    ports:
      - "3001:3001"

  frontend:
    build: ./front-end-service
    ports:
      - "3002:3002"