version: '3'

services:
  catalog-service:
    build:
      context: ./catalog-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./catalog-service:/app/catalog-service
      - ./catalog-service/BookDatabase.dp:/app/catalog-service/BookDatabase.dp

  order-service:
    build:
      context: ./order-service
    ports:
      - "3001:3001"
    depends_on:
      - catalog-service
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./order-service:/app/order-service
      - ./catalog-service:/app/catalog-service

 
